### ISSUE TITLE
Fork and republish

### ISSUE THREAD

**Issue by jg-l** [Patte1808/open_graph_parser#8]
Considering forking and republishing as this is not maintained.

If owner invites me to the project, I can maintain it

**Comment by Patte1808** [comment]
Hey,

> Considering forking and republishing as this is not maintained.
Yes, feel free to do that, thank you.

>If owner invites me to the project, I can maintain it
This is something I will unfortunately not do, as I don't know you and don't think it would be a trustworthy move from me.

However, once you forked and republished it I can mention the fork in the README and put the repository to read-only (as I should have done anyway)

**Comment by jg-l** [comment]
Fair enough on your points.

I have just created a new package as a general metadata parser. But a few snippets were lifted from your implementation. But the design is different so it didn't warrant an appropriate fork.

I've given you credit for the inspiration of course.

Check it out here https://github.com/jg-l/metadata_fetch. It's published on pub.dev but its taking awhile to show up.

**Comment by Patte1808** [comment]
Nice, thanks for your effort. I referenced your library in the README. :-)

**Comment by jg-l** [comment]
> Nice, thanks for your effort. I referenced your library in the README. :-)

Cheers!
